CREATE TABLE provider
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(50)                             NOT NULL UNIQUE,
    address        VARCHAR(255)                            NOT NULL,
    phone          VARCHAR(10)                             NOT NULL,
    email          VARCHAR(255)                            NOT NULL
);