-- product table
CREATE TYPE product_status AS ENUM ('PRE_ORDER', 'FOR_SALE', 'DISCONTINUED');
CREATE TABLE product
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    packing             VARCHAR(255)                            NOT NULL,
    category_id         BIGINT                                  NOT NULL,
    manufacturer        VARCHAR(255)                            NOT NULL,
    brand_origin        VARCHAR(255)                            NOT NULL,
    indications         VARCHAR(255)                            NOT NULL,
    registration_number VARCHAR(50)                             NOT NULL,
    uses                TEXT                                    NOT NULL,
    usage               TEXT                                    NOT NULL,
    side_effects        TEXT                                    NOT NULL,
    notes               TEXT                                    NOT NULL,
    storage             TEXT                                    NOT NULL,
    status              product_status                          NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE INDEX idx_name ON product (name);
CREATE INDEX idx_indications ON product (indications);
CREATE INDEX idx_uses ON product (uses);
CREATE INDEX idx_status ON product (status);

-- ingredient table

CREATE TABLE ingredient
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    amount     double precision                        NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_ingredient PRIMARY KEY (id),
    FOREIGN KEY (product_id) references product (id)
);

-- product_unit table

CREATE TABLE product_unit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id         BIGINT                                  NOT NULL,
    ratio           INTEGER                                 NOT NULL,
    sale_price      DOUBLE PRECISION                        NOT NULL,
    is_default_unit BOOLEAN                                 NOT NULL,
    product_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_unit PRIMARY KEY (id),
    FOREIGN KEY (product_id) references product (id),
    FOREIGN KEY (unit_id) references unit (id)
);

-- product image url

CREATE TABLE product_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_image PRIMARY KEY (id),
    FOREIGN KEY (product_id) references product (id)
);

