CREATE TABLE cart_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    CONSTRAINT pk_cart_item PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES Product (id),
    FOREIGN KEY (customer_id) REFERENCES Customer (id)
)