CREATE TYPE branch_status AS ENUM ('OPEN', 'CLOSED', 'MAINTENANCE');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE role_name AS ENUM ('STAFF', 'ADMIN');

CREATE TABLE branch
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    closing_hour   VARCHAR(10)                             NOT NULL,
    opening_hour   VARCHAR(10)                             NOT NULL,
    phone_number   VARCHAR(10)                             NOT NULL UNIQUE,
    status         branch_status                           NOT NULL DEFAULT 'OPEN',
    street_address VARCHAR(255)                            NOT NULL,
    ward           VARCHAR(255)                            NOT NULL,
    district       VARCHAR(255)                            NOT NULL,
    province       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_branch PRIMARY KEY (id)
);


CREATE INDEX idx_branch_status ON Branch (status);

CREATE TABLE customer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name      VARCHAR(50)                             NOT NULL,
    username       VARCHAR(50)                             NOT NULL UNIQUE,
    password       VARCHAR(60)                             NOT NULL,
    phone          VARCHAR(10)                             NOT NULL UNIQUE,
    is_active      BOOLEAN                                 NOT NULL DEFAULT TRUE,
    gender         gender                                  NOT NULL,
    street_address VARCHAR(255)                            NOT NULL,
    ward           VARCHAR(255)                            NOT NULL,
    district       VARCHAR(255)                            NOT NULL,
    province       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);
CREATE INDEX idx_customer_active ON Customer (is_active);

CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name role_name                               NOT NULL UNIQUE,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(50)                             NOT NULL,
    username  VARCHAR(50)                             NOT NULL UNIQUE,
    password  VARCHAR(60)                             NOT NULL,
    phone     VARCHAR(10)                             NOT NULL UNIQUE,
    is_active BOOLEAN                                 NOT NULL DEFAULT TRUE,
    gender    gender                                  NOT NULL,
    branch_id BIGINT,
    role_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES Branch (id),
    FOREIGN KEY (role_id) REFERENCES Role (id)
);
CREATE INDEX idx_employee_active ON Employee (is_active);
