CREATE INDEX idx_short_description ON product (short_description);
CREATE INDEX idx_full_description ON product (full_description);

CREATE INDEX idx_sale_price ON product_unit (sale_price);
CREATE INDEX idx_default_unit ON product_unit (is_default_unit);

CREATE TABLE import
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch_id      BIGINT                                  NOT NULL,
    invoice_number VARCHAR(255)                            NOT NULL,
    import_time    TIMESTAMP                               NOT NULL,
    employee_id    BIGINT                                  NOT NULL,
    provider_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_import PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch (id),
    FOREIGN KEY (employee_id) REFERENCES employee (id),
    FOREIGN KEY (provider_id) REFERENCES provider (id)
);

CREATE INDEX idx_invoice_number ON import (invoice_number);
CREATE INDEX idx_import_time ON import (import_time);

CREATE TABLE import_detail
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    import_id       BIGINT                                  NOT NULL,
    quantity        INTEGER                                 NOT NULL,
    expiration_date date                                    NOT NULL,
    product_id      BIGINT                                  NOT NULL,
    import_price    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_import_detail PRIMARY KEY (id),
    FOREIGN KEY (import_id) REFERENCES import (id),
    FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE INDEX idx_expiration_date ON import_detail (expiration_date);
CREATE INDEX idx_import_price ON import_detail (import_price);
