CREATE TABLE receiver
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    name            VARCHAR(50)                             NOT NULL,
    phone           VARCHAR(10)                             NOT NULL,
    street_address  VARCHAR(255)                            NOT NULL,
    ward            VARCHAR(255)                            NOT NULL,
    district        VARCHAR(255)                            NOT NULL,
    province        VARCHAR(255)                            NOT NULL,
    is_primary      BOOLEAN                                 NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES Customer (id),
);

CREATE TYPE order_status AS ENUM ('PROCESSING', 'SHIPPING', 'DELIVERED', 'CANCELLED');

CREATE TABLE order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    receiver_id     BIGINT                                  NOT NULL,
    total_price     INT                                     NOT NULL,
    order_date      DATETIME                                NOT NULL,
    delivered_date  VARCHAR(255)                            NOT NULL,
    status          order_status                            NOT NULL DEFAULT 'PROCESSING',
    FOREIGN KEY (customer_id) REFERENCES Customer (id),
    FOREIGN KEY (receiver_id) REFERENCES Receiver (id),
);

CREATE TABLE order_detail
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    unit_id     BIGINT                                  NOT NULL,
    price       INT                                     NOT NULL,
    quantity    INT                                     NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Order (id),
    FOREIGN KEY (product_id) REFERENCES Product (id),
    FOREIGN KEY (unit_id) REFERENCES Unit (id)
);