CREATE TABLE receiver
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    name           VARCHAR(50)                             NOT NULL,
    phone          VARCHAR(10)                             NOT NULL,
    street_address VARCHAR(255)                            NOT NULL,
    ward           VARCHAR(255)                            NOT NULL,
    district       VARCHAR(255)                            NOT NULL,
    province       VARCHAR(255)                            NOT NULL,
    is_primary     BOOLEAN                                 NOT NULL DEFAULT false,
    latitude       DECIMAL(9, 6)                           NOT NULL DEFAULT 16.07,
    longitude      DECIMAL(9, 6)                           NOT NULL DEFAULT 108.15,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES Customer (id)
);

CREATE TYPE order_status AS ENUM ('PENDING', 'PROCESSING', 'SHIPPING', 'DELIVERED', 'CANCELLED');

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    receiver_id    BIGINT                                  NOT NULL,
    order_time     TIMESTAMP                               NOT NULL,
    ship_time      TIMESTAMP,
    delivered_time TIMESTAMP,
    status         order_status                            NOT NULL DEFAULT 'PENDING',
    branch_id      BIGINT                                  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES Customer (id),
    FOREIGN KEY (receiver_id) REFERENCES Receiver (id),
    FOREIGN KEY (branch_id) REFERENCES Branch (id)
);

CREATE TABLE "order_item"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id      BIGINT                                  NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    unit_id       BIGINT                                  NOT NULL,
    price         INT                                     NOT NULL,
    quantity      INT                                     NOT NULL,
    base_quantity INT                                     NOT NULL,
    expirate_date DATE                                    NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders (id),
    FOREIGN KEY (product_id) REFERENCES Product (id),
    FOREIGN KEY (unit_id) REFERENCES Unit (id)
);