CREATE TABLE reviews
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content          TEXT,
    created_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_id       BIGINT NOT NULL,
    customer_id      BIGINT,
    parent_review_id BIGINT,
    rating           INT,
    employee_id      BIGINT,
    FOREIGN KEY (product_id) REFERENCES product (id),
    FOREIGN KEY (customer_id) REFERENCES customer (id),
    FOREIGN KEY (parent_review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employee (id)
);

CREATE INDEX idx_review_product_id ON reviews (product_id);
