CREATE TABLE IF NOT EXISTS verification_token
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    token           VARCHAR(256)                             NOT NULL,
    expiration_time DATE,
    customer_id     BIGINT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE UNIQUE INDEX  idx_verification_token_token ON verification_token (token);