ALTER TYPE order_status ADD VALUE 'COMPLETED';

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS complete_time TIMESTAMP WITH TIME ZONE;

ALTER TABLE orders
    ALTER COLUMN complete_time TYPE TIMESTAMP WITH TIME ZONE USING complete_time AT TIME ZONE 'UTC';