CREATE TABLE notification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time TIMESTAMP with time zone                NOT NULL,
    url          VARCHAR(255)                            NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    employee_id  BIGINT                                  NOT NULL,
    read         BOOLEAN                                 NOT NULL,
    image        VARCHAR(255),
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);